routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//ROUTE GROUP FOR ADMIN
//SEMUA ROUTE DI DALAM ROUTE INI DIAKSES DENGAN "/admin/..."
Route::prefix('admin')->namespace('Admin')->group(function () {
	Auth::routes();

	Route::middleware('auth')->group(function () {

		Route::get('/', 'DashboardController@index')->name('dashboard');

		Route::resource('/siswa', 'SiswaController');

		Route::resource('/indikator', 'IndikatorController');

		Route::resource('/pertanyaan', 'PertanyaanController');

		Route::get('/rekap', 'RekapController@index')->name('rekap.index');
		Route::get('/rekap/print', 'RekapController@printPDF')->name('rekap.print');
		Route::get('/rekap/{id}', 'RekapController@show')->name('rekap.show');
		Route::delete('/rekap/{id}', 'RekapController@destroy')->name('rekap.destroy');

	});

	
});



//ROUTE UNTUK FRONTEND

Route::name('siswa.')->group(function () {

	Route::get('/', 'MainController@index');

	Route::get('/login', 'LoginController@showLoginForm')->name('login');
	Route::post('/login', 'LoginController@siswaLogin');
	Route::get('/register', 'LoginController@showRegistrationForm')->name('register');
	Route::post('/register', 'LoginController@siswaRegister');

	Route::middleware('siswa')->group(function () {

		//ROUTE FRONTEND YANG HARUS LOGIN TERLEBIH DAHULU
		Route::get('/tes', 'MainController@tes')->name('tes');
		Route::post('/tes', 'MainController@simpanTes');

		Route::get('/hasil-tes', 'MainController@hasilTes')->name('hasil-tes');

		Route::post('/logout', 'LoginController@logout')->name('logout');
	});

});

app/Siswa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Siswa extends Authenticatable
{
    protected $fillable = ['absen', 'nama', 'email', 'password','kelamin'];
    
    public function jawabans()
    {
        return $this->hasMany('App\Jawaban');
    }


    //PINDAH KE CONTROLLER
    // public function gayaBelajar(){
    // 	$jawabans = $this->jawabans->with('pertanyaan');

    // 	if (count($jawabans) > 0) {
    // 		foreach ($jawabans as $jawaban) {
    // 			return false;
    // 		}
    // 	}
    // }
}

app/Http/Controllers/Admin/SiswaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Siswa;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use App\Http\Controllers\Controller;

class SiswaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $siswas = Siswa::all();
        return view('admin.siswa.index', ['siswas' => $siswas]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.siswa.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'nama' => 'required|max:191',
            'absen' => 'required|integer|min:0|max:100',
            'email' => 'required|email|unique:siswas|max:191',
            'kelamin' => 'required|in:L,P',
            'password' => 'required'
        ]);

        $validatedData['password'] = Hash::make($validatedData['password']);
        $siswa = Siswa::create($validatedData);

        if ($siswa) {
            $request->session()->flash('toast', 'Tambah Siswa Berhasil');
            return redirect( route('siswa.show', [$siswa]) );
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Siswa  $siswa
     * @return \Illuminate\Http\Response
     */
    public function show(Siswa $siswa)
    {
        return view('admin.siswa.show', ['siswa' => $siswa]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Siswa  $siswa
     * @return \Illuminate\Http\Response
     */
    public function edit(Siswa $siswa)
    {
        return view('admin.siswa.edit', ['siswa' => $siswa]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Siswa  $siswa
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Siswa $siswa)
    {
        $validatedData = $request->validate([
            'nama' => 'required|max:191',
            'absen' => 'required|integer|min:0|max:100',
            'email' => 'required|email|max:191',
            'kelamin' => 'required|in:L,P',
            'password' => 'required'
        ]);

        if ($request->password != '') { //JIKA PASSWORD DI ISI MAKA GANTI PASSWORD
            $validatedData['password'] = Hash::make($validatedData['password']);
        }else{
            $validatedData['password'] = $siswa->password;
        }
        
        if ($siswa->update($validatedData)) {

            $request->session()->flash('toast', 'Edit Siswa Berhasil');
            return redirect( route('siswa.show', [$siswa]) );
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Siswa  $siswa
     * @return \Illuminate\Http\Response
     */
    public function destroy(Siswa $siswa)
    {
        if ($siswa->delete()) {
            return redirect( route('siswa.index') );
        }else{
            abort(500, 'Delete Indikator '.$siswa->name.' Error. Hubungi Administrator');
        }
    }
}

resources/views/admin/siswa/_form.blade.php
@csrf
<div class="form-group">
	<label for="absen" class="control-label">No. Absen</label>
	<input type="number" min="1" class="form-control @error('absen') is-invalid @enderror" id="absen" name="absen" placeholder="Nomor Absen" value="{{  old('absen') }}" required autofocus>
</div>

<div class="form-group">
	<label for="kelas" class="control-label">Kelas</label>
	<input type="text" class="form-control @error('kelas') is-invalid @enderror" id="kelas" name="kelas" placeholder="Kelas" value="{{ old('kelas') }}" required>
</div>

<div class="form-group">
	<label for="nama" class="control-label">Nama</label>
	<input type="text" class="form-control @error('nama') is-invalid @enderror" id="nama" name="nama" placeholder="Nama Lengkap" value="{{  old('nama') }}" required>
</div>

<div class="form-group">
	<label for="email" class="control-label">E-Mail</label>
	<input type="email" class="form-control @error('email') is-invalid @enderror" id="email" name="email" placeholder="E-mail" value="{{  old('email') }}" required>
</div>

<div class="form-group">
	<label for="kelamin" class="control-label">Kelamin</label>
	<select id="kelamin" name="kelamin" class="form-control @error('kelamin') is-invalid @enderror" required>
		<option value=""></option>
		<option value="L" {!! old('kelamin') == 'L' ? 'selected' : '' !!}>Laki-Laki</option>
		<option value="P" {!! old('kelamin') == 'P' ? 'selected' : '' !!}>Perempuan</option>
	</select>
</div>

<div class="form-group">
	<label for="password" class="control-label">Password</label>
	<input type="password" class="form-control" id="password" name="password" placeholder="Password" value="" 
		{!! \Request::is('admin/siswa/*/edit') ? '' : 'required' !!}>
	@if(\Request::is('admin/siswa/*/edit'))
	<span class="small">Silahkan isi untuk mengganti password, atau biarkan kosong.</span>
	@endif
</div>

<button type="submit" class="btn btn-info">Simpan</button>

resources/views/admin/siswa/create.blade.php
@extends('layouts.admin')

@section('title', 'Tambah Siswa')

@section('content')
<div class="row">
    <div class="col-lg-6 col-md-6">
        <form action="{{ route('siswa.store') }}" method="POST">
            @include('admin.siswa._form')
        </form>
    </div>

    <div class="col-lg-6 col-md-6">
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
    </div>
</div>
@endsection

resources/views/admin/siswa/edit.blade.php
@extends('layouts.admin')

@section('title', 'Edit Siswa')

@section('content')
<div class="row">
    <div class="col-lg-6 col-md-6">
        <form action="{{ route('siswa.update', [$siswa]) }}" method="POST">
            @method('PATCH')
            @include('admin.siswa._form')
        </form>
    </div>

    <div class="col-lg-6 col-md-6">
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
    </div>
</div>
@endsection

resources/views/admin/siswa/index.blade.php
@extends('layouts.admin')

@section('title')
Data Siswa (<small class="text-gray">Total : {{ count($siswas) }}</small>)
@endsection

@section('content')
<div>
    <a href="{{ route('siswa.create') }}" class="btn btn-success">Tambah Siswa</a>
</div>
<br>
<div class="card card-info">
    <div class="card-header">
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <div class="row">
            <div class="col-lg-12">
                <table id="datatable" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>No. Absen</th>
                            <th>Nama</th>
                            <th>Kelamin</th>
                            <th style="width: 150px;">Action</th>
                        </tr>
                    </thead>
                    <tbody>

                    @foreach ($siswas as $siswa)
                    <tr>
                        <td>{{ $siswa->absen }}</td>
                        <td>{{ $siswa->nama }}</td>
                        <td>{{ $siswa->kelamin }}</td>
                        <td>
                            <a href="{{ route('siswa.show', [$siswa]) }}" class="btn btn-sm btn-success"><i class="fas fa-eye"></i></a>
                            <a href="{{ route('siswa.edit', [$siswa]) }}" class="btn btn-sm btn-primary"><i class="fas fa-edit"></i></a>
                            <a href="{{ route('siswa.destroy', [$siswa]) }}" 
                                onclick="event.preventDefault(); if(confirm('Anda yakin ingin menghapus siswa : {{ $siswa->nama }} ?')) {
                                    document.getElementById('delete-siswa-{{ $siswa->id }}').submit();
                                }"
                                class="btn btn-danger btn-sm">
                                <i class="fas fa-trash-alt"></i>
                            </a>

                            <form id="delete-siswa-{{ $siswa->id }}" action="{{ route('siswa.destroy', [$siswa]) }}" method="POST" style="display: none;">
                                @csrf
                                @method('DELETE')
                            </form>
                        </td>
                    </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!--End Card Body-->
</div>
@endsection


@section('css')
@parent
    <!-- summernote -->
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/datatables/dataTables.bootstrap4.min.css') }}">
@endsection

@section('js')
@parent
    <!-- DataTable -->
    <script src="{{ asset('adminlte/plugins/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('adminlte/plugins/datatables/dataTables.bootstrap4.min.js') }}"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('#datatable').DataTable({
          "columnDefs": [
            { "orderable": false, "targets": 3 }
          ]
        });
    } );
</script>
@endsection

resources/views/admin/siswa/show.blade.php
@extends('layouts.admin')

@section('title')
Siswa : {{ $siswa->nama }}
@endsection

@section('content')
<div>
    <a href="{{ route('siswa.edit', [$siswa]) }}" class="btn btn-primary">Edit siswa</a>
    <a href="{{ route('siswa.destroy', [$siswa]) }}" 
        onclick="event.preventDefault(); if(confirm('Anda yakin ingin menghapus {{ $siswa->nama }} ?')) {
            document.getElementById('delete-siswa-{{ $siswa->id }}').submit();
        }"
        class="btn btn-danger">Hapus siswa</a>

    <form id="delete-siswa-{{ $siswa->id }}" action="{{ route('siswa.destroy', [$siswa]) }}" method="POST" style="display: none;">
        @csrf
        @method('DELETE')
    </form>
</div>
<br>
<div class="row">
    <div class="col-lg-8 col-md-8">
        <table class="table bordered">
            <tr>
                <th>No. Absen :</th>
                <td>{{ $siswa->absen }}</td>
            </tr>
            <tr>
                <th>Nama Siswa :</th>
                <td>{{ $siswa->nama }}</td>
            </tr>
            <tr>
                <th>E-Mail :</th>
                <td>{{ $siswa->email }}</td>
            </tr>
            <tr>
                <th>Jenis Kelamin :</th>
                <td>{!! $siswa->kelamin == 'L' ? 'Laki-Laki' : 'Perempuan' !!}</td>
            </tr>
        </table>
    </div>
</div>
@endsection