routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//ROUTE GROUP FOR ADMIN
//SEMUA ROUTE DI DALAM ROUTE INI DIAKSES DENGAN "/admin/..."
Route::prefix('admin')->namespace('Admin')->group(function () {
	Auth::routes();

	Route::middleware('auth')->group(function () {

		Route::get('/', 'DashboardController@index')->name('dashboard');

		Route::resource('/siswa', 'SiswaController');

		Route::resource('/indikator', 'IndikatorController');

		Route::resource('/pertanyaan', 'PertanyaanController');

		Route::get('/rekap', 'RekapController@index')->name('rekap.index');
		Route::get('/rekap/print', 'RekapController@printPDF')->name('rekap.print');
		Route::get('/rekap/{id}', 'RekapController@show')->name('rekap.show');
		Route::delete('/rekap/{id}', 'RekapController@destroy')->name('rekap.destroy');

	});

	
});



//ROUTE UNTUK FRONTEND

Route::name('siswa.')->group(function () {

	Route::get('/', 'MainController@index');

	Route::get('/login', 'LoginController@showLoginForm')->name('login');
	Route::post('/login', 'LoginController@siswaLogin');
	Route::get('/register', 'LoginController@showRegistrationForm')->name('register');
	Route::post('/register', 'LoginController@siswaRegister');

	Route::middleware('siswa')->group(function () {

		//ROUTE FRONTEND YANG HARUS LOGIN TERLEBIH DAHULU
		Route::get('/tes', 'MainController@tes')->name('tes');
		Route::post('/tes', 'MainController@simpanTes');

		Route::get('/hasil-tes', 'MainController@hasilTes')->name('hasil-tes');

		Route::post('/logout', 'LoginController@logout')->name('logout');
	});

});

app/Pertanyaan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pertanyaan extends Model
{
    protected $fillable = ['indikator_id', 'pertanyaan', 'sifat'];
    public $timestamps = false;

    public function indikator()
    {
        return $this->belongsTo('App\Indikator');
    }

    public function jawabans(){
    	return $this->hasMany('App\Jawaban');
    }
	
	public function getKodeAttribute(){
		return 'C'.$this->id;
	}
}

app/Http/Controllers/Admin/PertanyaanController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Pertanyaan;
use App\Indikator;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PertanyaanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $indikators = Indikator::all();
        return view('admin.pertanyaan.index', [
            'indikators' => $indikators
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $indikators = Indikator::all();
        return view('admin.pertanyaan.create', ['indikators' => $indikators]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'indikator_id' => 'required',
            'pertanyaan' => 'required',
            'sifat' => 'required|in:positif,negatif'
        ]);
        $pertanyaan = Pertanyaan::create($validatedData);

        if ($pertanyaan) {

            $request->session()->flash('toast', 'Tambah Pertanyaan Berhasil');
            return redirect( route('pertanyaan.show', [$pertanyaan]) );
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Pertanyaan  $pertanyaan
     * @return \Illuminate\Http\Response
     */
    public function show(Pertanyaan $pertanyaan)
    {
        return view('admin.pertanyaan.show', ['pertanyaan' => $pertanyaan]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Pertanyaan  $pertanyaan
     * @return \Illuminate\Http\Response
     */
    public function edit(Pertanyaan $pertanyaan)
    {
        $indikators = Indikator::all();
        return view('admin.pertanyaan.edit', [
            'pertanyaan' => $pertanyaan,
            'indikators' => $indikators
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Pertanyaan  $pertanyaan
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Pertanyaan $pertanyaan)
    {
        $validatedData = $request->validate([
            'indikator_id' => 'required',
            'pertanyaan' => 'required',
            'sifat' => 'required|in:positif,negatif'
        ]);

        if ($pertanyaan->update($validatedData)) {
            $request->session()->flash('toast', 'Edit Pertanyaan Berhasil');
            return redirect( route('pertanyaan.show', [$pertanyaan]) );
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Pertanyaan  $pertanyaan
     * @return \Illuminate\Http\Response
     */
    public function destroy(Pertanyaan $pertanyaan)
    {
        if ($pertanyaan->delete()) {
            return redirect( route('pertanyaan.index') );
        }else{
            abort(500, 'Delete Pertanyaan '.$pertanyaan->id.' Error. Hubungi Administrator');
        }
    }
}

resources/views/admin/pertanyaan/_form.blade.php
@csrf

<div class="form-group">
	<label for="pertanyaan" class="control-label">Pertanyaan</label>
	<input type="text" class="form-control" id="pertanyaan" name="pertanyaan" placeholder="Pertanyaan" value="{{ @$pertanyaan->pertanyaan }}" autofocus>
</div>

<div class="form-group">
	<label for="indikator_id" class=" control-label">Indikator</label>
	<select id="indikator_id" name="indikator_id" class="form-control">
		<option value=""></option>
		@foreach($indikators as $indikator)
		<option value="{{ $indikator->id }}" {!! $indikator->id == @$pertanyaan->indikator_id ? 'selected' : '' !!}>
			{{ $indikator->nama }}</option>
		@endforeach
	</select>
</div>


<div class="form-group">
	<label for="sifat" class=" control-label">Sifat</label>
	<select id="sifat" name="sifat" class="form-control">
		<option value=""></option>
		<option value="positif" {!! @$pertanyaan->sifat == 'positif' ? 'selected' : '' !!}>Positif</option>
		<option value="negatif" {!! @$pertanyaan->sifat == 'negatif' ? 'selected' : '' !!}>Negatif</option>
	</select>
</div>

<button type="submit" class="btn btn-info">Simpan</button>

resources/views/admin/pertanyaan/create.blade.php
@extends('layouts.admin')

@section('title', 'Tambah Pertanyaan')

@section('content')
<div class="row">
    <div class="col-lg-6">
        <form action="{{ route('pertanyaan.store') }}" method="POST">
            @include('admin.pertanyaan._form')
        </form>
    </div>

    <div class="col-lg-6">
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
    </div>
</div>
@endsection

resources/views/admin/pertanyaan/edit.blade.php
@extends('layouts.admin')

@section('title', 'Edit Pertanyaan')

@section('content')
<div class="row">
    <div class="col-lg-6">
        <form action="{{ route('pertanyaan.update', [$pertanyaan]) }}" method="POST">
            @method('PATCH')
            @include('admin.pertanyaan._form')
        </form>
    </div>

    <div class="col-lg-6">
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
    </div>
</div>
@endsection

resources/views/admin/pertanyaan/index.blade.php
@extends('layouts.admin')

@section('title', 'Data Pertanyaan')

@section('content')
<div>
    <a href="{{ route('pertanyaan.create') }}" class="btn btn-success">Tambah Pertanyaan</a>
</div>
<br>
<div class="row">
    <div class="col-lg-12">
        @foreach($indikators as $indikator)
        <div class="card card-info">
            <div class="card-header">
                <h3 class="card-title">
                <small>Pertanyaan Indikator</small> : <b>{{$indikator->nama}} <small>({{count($indikator->pertanyaans)}})</small></b>
                </h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <table id="datatable-{{$indikator->nama}}" class="table table-bordered">
                        <thead>
                        <tr>
                            <th>No</th>
							<th>Kode</th>
                            <th>Pertanyaan</th>
                            <th style="width:130px">Action</th>
                        </tr>
                        </thead>
                        <tbody>

                        @foreach ($indikator->pertanyaans as $pertanyaan)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
							<td>{{ $pertanyaan->kode }}</td>
                            <td>{{ $pertanyaan->pertanyaan }} ({!! $pertanyaan->sifat == 'positif' ? '<span class="text-success"><b>+</b></span>' : '<span class="text-danger"><b>-</b></span>' !!})</td>
                            <td>
                                <a href="{{ route('pertanyaan.show', [$pertanyaan]) }}" class="btn btn-sm btn-success"><i class="fas fa-eye"></i></a>
                                <a href="{{ route('pertanyaan.edit', [$pertanyaan]) }}" class="btn btn-sm btn-primary"><i class="fas fa-edit"></i></a>
                                <a href="{{ route('pertanyaan.destroy', [$pertanyaan]) }}" 
                                    onclick="event.preventDefault(); if(confirm('Anda yakin ingin menghapus pertanyaan ini ?')) {
                                        document.getElementById('delete-pertanyaan-{{ $pertanyaan->id }}').submit();
                                    }"
                                    class="btn btn-danger btn-sm">
                                    <i class="fas fa-trash-alt"></i>
                                </a>

                                <form id="delete-pertanyaan-{{ $pertanyaan->id }}" action="{{ route('pertanyaan.destroy', [$pertanyaan]) }}" method="POST" style="display: none;">
                                    @csrf
                                    @method('DELETE')
                                </form>
                            </td>
                        </tr>
                        @endforeach
                        </tbody>
                    </table>
            </div>
            <!-- /.card-body -->
        </div>
        <br>
        <br>
        @endforeach
    </div>
</div>

@endsection



@section('css')
@parent
    <!-- summernote -->
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/datatables/dataTables.bootstrap4.min.css') }}">
@endsection

@section('js')
@parent
    <!-- DataTable -->
    <script src="{{ asset('adminlte/plugins/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('adminlte/plugins/datatables/dataTables.bootstrap4.min.js') }}"></script>
<script type="text/javascript">
    $(document).ready(function() {

        @foreach($indikators as $indikator)
            $('#datatable-{{$indikator->nama}}').DataTable({
              "columnDefs": [
                { "orderable": false, "targets": 3 }
              ]
            });

        @endforeach
    } );
</script>
@endsection

resources/views/admin/pertanyaan/show.blade.php
@extends('layouts.admin')

@section('title')
Pertanyaan : {{ $pertanyaan->id }}
@endsection

@section('content')
<div>
    <a href="{{ route('pertanyaan.edit', [$pertanyaan]) }}" class="btn btn-primary">Edit Pertanyaan</a>
    <a href="{{ route('pertanyaan.destroy', [$pertanyaan]) }}" 
        onclick="event.preventDefault(); if(confirm('Anda yakin ingin menghapus pertanyaan {{ $pertanyaan->id }} ?')) {
            document.getElementById('delete-pertanyaan-{{ $pertanyaan->id }}').submit();
        }"
        class="btn btn-danger">Hapus Pertanyaan</a>

    <form id="delete-pertanyaan-{{ $pertanyaan->id }}" action="{{ route('pertanyaan.destroy', [$pertanyaan]) }}" method="POST" style="display: none;">
        @csrf
        @method('DELETE')
    </form>
</div>
<br>
<div class="row">
    <div class="col-lg-8 col-md-8">
        <table class="table bordered">
            <tr>
                <th style="min-width: 200px">Indikator :</th>
                <td>{{ $pertanyaan->indikator->nama }}</td>
            </tr>
            <tr>
                <th style="min-width: 200px">Pertanyaan :</th>
                <td>{{ $pertanyaan->pertanyaan }}</td>
            </tr>
            <tr>
                <th>Sifat :</th>
                <td>{{ $pertanyaan->sifat }}</td>
            </tr>
        </table>
    </div>
</div>
@endsection