routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//ROUTE GROUP FOR ADMIN
//SEMUA ROUTE DI DALAM ROUTE INI DIAKSES DENGAN "/admin/..."
Route::prefix('admin')->namespace('Admin')->group(function () {
	Auth::routes();

	Route::middleware('auth')->group(function () {

		Route::get('/', 'DashboardController@index')->name('dashboard');

		Route::resource('/siswa', 'SiswaController');

		Route::resource('/indikator', 'IndikatorController');

		Route::resource('/pertanyaan', 'PertanyaanController');

		Route::get('/rekap', 'RekapController@index')->name('rekap.index');
		Route::get('/rekap/print', 'RekapController@printPDF')->name('rekap.print');
		Route::get('/rekap/{id}', 'RekapController@show')->name('rekap.show');
		Route::delete('/rekap/{id}', 'RekapController@destroy')->name('rekap.destroy');

	});

	
});



//ROUTE UNTUK FRONTEND

Route::name('siswa.')->group(function () {

	Route::get('/', 'MainController@index');

	Route::get('/login', 'LoginController@showLoginForm')->name('login');
	Route::post('/login', 'LoginController@siswaLogin');
	Route::get('/register', 'LoginController@showRegistrationForm')->name('register');
	Route::post('/register', 'LoginController@siswaRegister');

	Route::middleware('siswa')->group(function () {

		//ROUTE FRONTEND YANG HARUS LOGIN TERLEBIH DAHULU
		Route::get('/tes', 'MainController@tes')->name('tes');
		Route::post('/tes', 'MainController@simpanTes');

		Route::get('/hasil-tes', 'MainController@hasilTes')->name('hasil-tes');

		Route::post('/logout', 'LoginController@logout')->name('logout');
	});

});

app/Http/Controllers/MainController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Pertanyaan;
use App\Jawaban;
use App\Indikator;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class MainController extends Controller
{
    /**
     * Menampilkan Halaman Utama Aplikasi.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('main.index');
    }

    /**
     * Menampilkan Halaman Utama Aplikasi.
     *
     * @return \Illuminate\Http\Response
     */
    public function tes()
    {
        $pertanyaans = Pertanyaan::all();
        return view('main.tes', [
            'pertanyaans' => $pertanyaans,
        ]);
    }

    /**
     * Menyimpan Hasil Tes User.
     *
     * @return \Illuminate\Http\Response
     */
    public function simpanTes(Request $request)
    {
        $siswa = Auth::guard('siswa')->user();
        
        $inputan_jawaban = [];

        foreach ($request->input('jawaban') as $pertanyaan_id => $nilai_jawaban) {

            $inputan_jawaban[] = [
                'siswa_id' => $siswa->id,
                'pertanyaan_id' => $pertanyaan_id,
                'jawaban' => $nilai_jawaban
            ];
        }
        $siswa->jawabans()->delete();
        if($siswa->jawabans()->createMany($inputan_jawaban)){
            return redirect(route('siswa.hasil-tes'));
        }
    }

    /**
     * Menampilkan Hasil Tes User.
     *
     * @return \Illuminate\Http\Response
     */
    public function hasilTes(Request $request)
    {
        $siswa = Auth::guard('siswa')->user();

        $jml_pertanyaan = DB::table('pertanyaans')
                     ->select(DB::raw('indikator_id, sifat, count(*) as jumlah, (count(*) * 4) nilai_max'))
                     ->groupBy('sifat', 'indikator_id')
                     ->get();

        $jml_jawaban = DB::table('jawabans')
                     ->select(DB::raw('indikator_id, sifat, SUM(jawaban) nilai'))
                     ->join('pertanyaans', 'jawabans.pertanyaan_id', '=', 'pertanyaans.id')
                     ->where('siswa_id', $siswa->id)
                     ->groupBy('indikator_id', 'sifat')
                     ->get();

        //HITUNG PERSENTASE
        $persentase = [];
        foreach ($jml_pertanyaan as $val) {
            if (!isset($persentase[$val->indikator_id]['positif'])) {
                $persentase[$val->indikator_id]['positif'] = 0;
            }

            if (!isset($persentase[$val->indikator_id]['negatif'])) {
                $persentase[$val->indikator_id]['negatif'] = 0;
            }

            $persentase[$val->indikator_id][$val->sifat] = $val->nilai_max;
        }

        foreach ($jml_jawaban as $val) {
			$nilai_maximal = $persentase[$val->indikator_id][$val->sifat];
			$nilai_siswa = $val->nilai;
            $persentase[$val->indikator_id][$val->sifat] = ($nilai_siswa * 100) / $nilai_maximal;
        }
        //END HITUNG PERSENTASI
		


        //MENENTUKAN INDIKATOR (GAYA BELAJAR)
        //step 1 tentukan nilai positif tertinggi
        $indikator_id_pos_tertinggi = NULL;
        $pos = 0;
        foreach ($persentase as $id_indikator => $val) {
            if ($val['positif'] > $pos) {
                $indikator_id_pos_tertinggi = $id_indikator;
                $pos = $val['positif'];
            }
        }

        //step 2 bandingkan nilai positif & negatif
        $indikator = Indikator::find($indikator_id_pos_tertinggi);
        $siswa->indikator_id = $indikator->id;
        $siswa->save();


        return view('main.hasil-tes', ['indikator' => $indikator, 'persentase' => $persentase[$indikator_id_pos_tertinggi]]);
    }
}

resources/views/main/hasil-tes.blade.php
@extends('layouts.main')

@section('content')
<div class="row">
    <div class="col-md-12">
        @if($indikator)
        <h1><small>Gaya Belajar Anda</small> : <b><u>{{ $indikator->nama }} ({{ round($persentase['positif'], 2) }}%)</u></b></h1>
        <div class="text-center">
            @switch($indikator->nama)
                @case('Visual')
                    <img src="{{ asset('images/gaya-visual.png') }}">
                    @break

                @case('Auditorial')
                    <img src="{{ asset('images/gaya-auditorial.png') }}">
                    @break

                @case('Kinestetik')
                    <img src="{{ asset('images/gaya-kinestetik.png') }}">
                    @break
            @endswitch
        </div>
        <div>
            @if($persentase['positif'] > $persentase['negatif'])
            <p><b>Tentang Gaya Belajar {{ $indikator->nama }}</b></p>
            {!! $indikator->deskripsi !!}
            @else
            <p><b>Saran Untuk Anda</b></p>
            {!! $indikator->saran !!}
            @endif
        </div>
        @endif

        <div class="form-group text-center">
            <span>Tidak sesuai untuk anda ? </span>
            <a href="{{ route('siswa.tes') }}" class="btn btn-success btn-sm">Tes Ulang</a>
        </div>
    </div>
</div>
@endsection

resources/views/main/index.blade.php
@extends('layouts.main')

@section('content')
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="http://placehold.it/900x500/39CCCC/ffffff&text=I+Love+Bootstrap" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="http://placehold.it/900x500/3c8dbc/ffffff&text=I+Love+Bootstrap" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="http://placehold.it/900x500/f39c12/ffffff&text=I+Love+Bootstrap" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="row">
  <div class="col-lg-12 text-center">
    <br>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus cursus libero et commodo. Nullam congue non sem quis commodo. Fusce pretium magna posuere ante porta, ut pulvinar felis volutpat. Ut non eleifend lacus. Sed dictum, sem eget accumsan finibus, ipsum ipsum tristique nisl, sed tristique augue elit nec mauris. Praesent facilisis ullamcorper quam ut blandit. Donec facilisis maximus faucibus.</p>
    @if(Auth::guard('siswa')->check())
      <a href="{{ route('siswa.tes') }}" class="btn btn-success">Mulai Tes Sekarang</a>
    @else
      <a href="{{ route('siswa.login') }}" class="btn btn-primary">Login</a>
    @endif
  </div>
</div>
@endsection

resources/views/main/login.blade.php
@extends('layouts.main')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Login') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('siswa.login') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email" autofocus>

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="current-password">

                                @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Login') }}
                                </button>

                                    <a class="btn btn-link" href="{{ route('siswa.register') }}">
                                        Belum punya akun? <b>Daftar !</b>
                                    </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/main/register.blade.php
@extends('layouts.main')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Register') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('siswa.register') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="absen" class="col-md-4 col-form-label text-md-right">{{ __('No. Absen') }}</label>

                            <div class="col-md-6">
                                <input type="number" min="1" class="form-control @error('nama') is-invalid @enderror" id="absen" name="absen" value="{{ old('absen') }}" required autofocus>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="kelas" class="col-md-4 col-form-label text-md-right">{{ __('Kelas') }}</label>

                            <div class="col-md-6">
                                <input type="number" min="1" class="form-control @error('kelas') is-invalid @enderror" id="kelas" name="kelas" value="{{ old('kelas') }}" required autofocus>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="nama" class="col-md-4 col-form-label text-md-right">{{ __('Nama Lengkap') }}</label>

                            <div class="col-md-6">
                                <input id="nama" type="text" class="form-control @error('nama') is-invalid @enderror" name="nama" value="{{ old('nama') }}" required autocomplete="nama">

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email">

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="new-password">

                                @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="kelamin" class="col-md-4 col-form-label text-md-right">{{ __('Jenis Kelamin') }}</label>

                            <div class="col-md-6">
                                <select id="kelamin" name="kelamin" class="form-control" required>
                                    <option value=""></option>
                                    <option value="L" {{ (old("kelamin") == "L" ? "selected":"") }}>Laki-Laki</option>
                                    <option value="P" {{ (old("kelamin") == "P" ? "selected":"") }}>Perempuan</option>
                                </select>
                            </div>
                        </div>


                        

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Register') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/main/tes.blade.php
@extends('layouts.main')

@section('css')
    @parent
    <style type="text/css">
        #pertanyaan th{
            text-align: center;
            vertical-align: middle;
        }
    </style>
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/icheck-bootstrap/green.css') }}">
@endsection


@section('content')
<div>
    <p>Silahkan isi pertanyaan-pertanyaan berikut untuk mengetahui gaya belajar anda.</p>
</div>

<div class="row">
    <div class="col-md-12">
        <form method="POST" action="{{ route('siswa.tes') }}">
            @csrf
        <table id="pertanyaan" class="table table-bordered">
            <tr>
                <th rowspan="2" width="10px">No.</th>
                <th rowspan="2">Pertanyaan</th>
                <th colspan="4">Jawaban</th>
            </tr>
            <tr>
                <th width="100">Sangat Setuju</th>
                <th width="100">Setuju</th>
                <th width="100">Kurang Setuju</th>
                <th width="100">Tidak Setuju</th>
            </tr>
            @foreach($pertanyaans as $pertanyaan)
            <tr>
                <td class="text-center">{{ $loop->iteration }}</td>
                <td>{{ $pertanyaan->pertanyaan }} {{$pertanyaan->sifat}}</td>
                <td class="text-center"><input type="radio" name="jawaban[{{ $pertanyaan->id }}]" value="4"></td>
                <td class="text-center"><input type="radio" name="jawaban[{{ $pertanyaan->id }}]" value="3"></td>
                <td class="text-center"><input type="radio" name="jawaban[{{ $pertanyaan->id }}]" value="2"></td>
                <td class="text-center"><input type="radio" name="jawaban[{{ $pertanyaan->id }}]" value="1"></td>
            </tr>
            @endforeach
        </table>

        <div class="form-group text-right">
            <input type="submit" class="btn btn-success" value="Lihat Hasil Tes">
        </div>
        </form>
    </div>
</div>
@endsection



@section('js')
    @parent

    <script src="{{ asset('adminlte/plugins/icheck-bootstrap/icheck.min.js') }}"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('input').iCheck({
                checkboxClass: 'icheckbox_square-green',
                radioClass: 'iradio_square-green',
                increaseArea: '20%' // optional
            });
        });
    </script>
@endsection